{\rtf1\ansi\ansicpg1252\cocoartf2868
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\froman\fcharset0 Times-Bold;\f1\froman\fcharset0 Times-Roman;\f2\froman\fcharset0 Times-BoldItalic;
\f3\fmodern\fcharset0 Courier;}
{\colortbl;\red255\green255\blue255;\red0\green0\blue0;}
{\*\expandedcolortbl;;\cssrgb\c0\c0\c0;}
\paperw11900\paperh16840\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\sa298\partightenfactor0

\f0\b\fs36 \cf0 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec2 Summary\
\pard\pardeftab720\sa240\partightenfactor0

\f1\b0\fs24 \cf0 Added NVIDIA Fabric Manager installation script for EC2 instances with NVLink/NVSwitch (A100/H100 GPUs). The script automatically detects NVIDIA driver version, installs the matching fabric manager package, and configures the service. This enables proper multi-GPU communication for high-performance computing workloads.\
\pard\pardeftab720\sa419\partightenfactor0

\f2\i\b\fs18 \cf0 [This description was generated by us.anthropic.claude-3-7-sonnet-20250219-v1:0]
\f0\i0 \
\pard\pardeftab720\sa298\partightenfactor0

\fs36 \cf0 Testing - GPU Setup & Verification\
\pard\pardeftab720\sa280\partightenfactor0

\fs28 \cf0 Non NV-Switch Node (g6.xlarge )\
\pard\pardeftab720\sa240\partightenfactor0

\fs24 \cf0 Command
\f1\b0 \
\pard\pardeftab720\sa240\partightenfactor0

\f3\fs26 \cf0 sky EC2 -y -c rangeev-test5 --num-nodes=1 --instance-type=g6.xlarge --infra aws/us-east-1 --env ENTRYPOINT="nvidia-smi"
\f1\fs24 \
\pard\pardeftab720\sa240\partightenfactor0

\f0\b \cf0 Fabric Installation Log
\f1\b0 \
\pard\pardeftab720\partightenfactor0

\f3\fs26 \cf0 (setup pid=16601) + bash /tmp/setup-fabric-manager.sh\
(setup pid=16601) === Fabric Manager Setup ===\
(setup pid=16601) Detected NVIDIA driver version: 570.195.03\
(setup pid=16601) Installing nvidia-fabricmanager matching driver version...\
(setup pid=16601) Installing exact match: nvidia-fabricmanager-570=570.195.03-1\
.\
.\
.\
(setup pid=16601) Created symlink /etc/systemd/system/multi-user.target.wants/nvidia-fabricmanager.service \uc0\u8594  /usr/lib/systemd/system/nvidia-fabricmanager.service.\
(setup pid=16601) Attempting to start fabric manager...\
(setup pid=16601) Fabric manager not started (no NVSwitch hardware present)\
\pard\pardeftab720\sa280\partightenfactor0

\f0\b\fs28 \cf0 NV-Switch Node (p4d.24xlarge)\
\pard\pardeftab720\sa240\partightenfactor0

\fs24 \cf0 Command
\f1\b0 \
\pard\pardeftab720\sa240\partightenfactor0

\f3\fs26 \cf0 sky EC2 -y -c rangeev-test6 --num-nodes=1 --instance-type=p4d.24xlarge --infra aws/us-east-1 --env ENTRYPOINT="nvidia-smi"
\f1\fs24 \
\pard\pardeftab720\sa240\partightenfactor0

\f0\b \cf0 Fabric Installation Log
\f1\b0 \
\pard\pardeftab720\partightenfactor0

\f3\fs26 \cf0 (setup pid=15562) + bash /tmp/setup-fabric-manager.sh\
(setup pid=15562) === Fabric Manager Setup ===\
(setup pid=15562) Detected NVIDIA driver version: 570.195.03\
(setup pid=15562) Installing nvidia-fabricmanager matching driver version...\
(setup pid=15562) Installing exact match: nvidia-fabricmanager-570=570.195.03-1\
.\
.\
.\
(setup pid=15562) Attempting to start fabric manager...\
(setup pid=15562) Fabric manager started successfully\
\pard\pardeftab720\sa240\partightenfactor0

\f0\b\fs24 \cf0 CUDA Availability Check
\f1\b0 \
\pard\pardeftab720\partightenfactor0

\f3\fs26 \cf0 root@ip-10-0-110-173:~/lab42_vr# python3\
Python 3.12.9 (main, Mar 17 2025, 21:01:58) [Clang 20.1.0 ] on linux\
Type "help", "copyright", "credits" or "license" for more information.\
>>> import torch\
>>> print(torch.cuda.is_available())\
True\
}